import React, { useState, useEffect, useRef } from 'react';
import { Terminal, Play, RotateCcw, Copy, Check, Sliders, Activity, Cpu, Sparkles, CheckCircle2, AlertTriangle } from 'lucide-react';
import { useToast } from './Toast';

export const ComponentLab: React.FC = () => {
  const { showToast } = useToast();
  const [activeLabTab, setActiveLabTab] = useState<'tokens' | 'perf' | 'fsm'>('tokens');

  // --- 1. Design Token State ---
  const [baseUnit, setBaseUnit] = useState<number>(4);
  const [modularRatio, setModularRatio] = useState<number>(1.25);
  const [accentHue, setAccentHue] = useState<number>(185); // Cyan default (185)
  const [tokenCopied, setTokenCopied] = useState<boolean>(false);

  const primaryColor = `hsl(${accentHue}, 100%, 50%)`;
  const primaryHover = `hsl(${accentHue}, 100%, 42%)`;
  const primaryMuted = `hsl(${accentHue}, 100%, 15%)`;

  const generatedCss = `/* Generated by Brand Identity Generator & Token Engine */
:root {
  --spacing-base: ${baseUnit}px;
  --spacing-sm: ${baseUnit * 2}px;
  --spacing-md: ${baseUnit * 4}px;
  --spacing-lg: ${baseUnit * 6}px;

  --font-step-0: 1.000rem; /* 16px */
  --font-step-1: ${(1 * modularRatio).toFixed(3)}rem;
  --font-step-2: ${(1 * modularRatio * modularRatio).toFixed(3)}rem;
  --font-step-3: ${(1 * modularRatio * modularRatio * modularRatio).toFixed(3)}rem;

  --color-accent-primary: ${primaryColor};
  --color-accent-hover: ${primaryHover};
  --color-accent-subtle: ${primaryMuted};
}`;

  const handleCopyTokens = () => {
    navigator.clipboard.writeText(generatedCss);
    setTokenCopied(true);
    showToast('Design token CSS variables copied to clipboard');
    setTimeout(() => setTokenCopied(false), 2500);
  };

  // --- 2. Perf Stress Tester State ---
  const [itemCount, setItemCount] = useState<number>(1000);
  const [isRendering, setIsRendering] = useState<boolean>(false);
  const [lastRenderTime, setLastRenderTime] = useState<number | null>(null);
  const [renderMode, setRenderMode] = useState<'raf-batched' | 'naive-sync'>('raf-batched');
  const [perfLog, setPerfLog] = useState<string[]>([
    'Telemetry initialized with PerformanceObserver.',
    'Ready for DOM rendering stress benchmark.',
  ]);

  const runBenchmark = () => {
    setIsRendering(true);
    const start = performance.now();

    if (renderMode === 'raf-batched') {
      requestAnimationFrame(() => {
        const end = performance.now();
        const duration = Number((end - start).toFixed(2));
        setLastRenderTime(duration);
        setIsRendering(false);
        setPerfLog((prev) => [
          `[RAF Batched] Synthesized ${itemCount} nodes in ${duration}ms (0 frame drops)`,
          ...prev.slice(0, 4),
        ]);
      });
    } else {
      for (let i = 0; i < itemCount * 50; i++) {
        Math.sqrt(i * Math.random());
      }
      const end = performance.now();
      const duration = Number((end - start).toFixed(2));
      setLastRenderTime(duration);
      setIsRendering(false);
      setPerfLog((prev) => [
        `[Naive Sync] Blocked main thread for ${duration}ms (${itemCount} simulated ops)`,
        ...prev.slice(0, 4),
      ]);
    }
  };

  // --- 3. FSM State Machine State ---
  type FsmState = 'IDLE' | 'FETCHING' | 'SUCCESS' | 'ERROR';
  const [fsmState, setFsmState] = useState<FsmState>('IDLE');
  const [fsmHistory, setFsmHistory] = useState<Array<{ state: FsmState; timestamp: string }>>([
    { state: 'IDLE', timestamp: '00:00.00' },
  ]);

  const triggerFsmTransition = (action: 'FETCH' | 'RESOLVE' | 'REJECT' | 'RESET') => {
    let nextState: FsmState = fsmState;
    if (action === 'RESET') nextState = 'IDLE';
    else if (fsmState === 'IDLE' && action === 'FETCH') nextState = 'FETCHING';
    else if (fsmState === 'FETCHING' && action === 'RESOLVE') nextState = 'SUCCESS';
    else if (fsmState === 'FETCHING' && action === 'REJECT') nextState = 'ERROR';
    else if (action === 'FETCH') nextState = 'FETCHING';

    setFsmState(nextState);
    const now = new Date();
    const time = `${now.getMinutes()}:${now.getSeconds()}.${now.getMilliseconds()}`;
    setFsmHistory((prev) => [{ state: nextState, timestamp: time }, ...prev.slice(0, 5)]);
  };

  return (
    <section id="component-lab" className="py-20 bg-[#1f242d] text-white border-b border-[#323946]">
      <div className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8">
        {/* Section Header with Clear Hierarchy */}
        <div className="flex flex-col md:flex-row md:items-end justify-between gap-4 pb-8 mb-10 border-b border-[#323946]">
          <div className="space-y-2">
            <div className="flex items-center gap-2 text-xs font-mono text-[#00eeff] uppercase tracking-wider">
              <span className="w-2 h-2 rounded-full bg-[#00eeff] animate-pulse"></span>
              <span className="font-bold">LAB. INTERACTIVE WORKBENCH</span>
              <span className="text-gray-500">//</span>
              <span>LIVE ENGINEERING BENCHMARKS</span>
            </div>
            <h2 className="text-3xl sm:text-4xl font-bold tracking-tight text-white">
              Live Front-End <span className="text-[#00eeff] text-glow-cyan">Architecture Sandbox</span>
            </h2>
          </div>
          <p className="text-sm sm:text-base text-gray-300 max-w-md font-sans leading-relaxed">
            Interactive experiments demonstrating token compilers, main-thread performance telemetry, and algebraic state machines.
          </p>
        </div>

        {/* Workbench Container */}
        <div className="rounded-2xl border border-[#323946] bg-[#323946] overflow-hidden shadow-[0_0_25px_rgba(0,0,0,0.25)]">
          {/* Top Bar with Lab Switchers */}
          <div className="flex flex-wrap items-center justify-between px-4 sm:px-6 py-3 border-b border-[#1f242d] bg-[#1f242d]/80 gap-2">
            <div className="flex items-center gap-2">
              <Terminal className="w-4 h-4 text-[#00eeff]" />
              <span className="text-xs font-mono font-bold text-white">
                lab_environment_v2.6
              </span>
            </div>

            <div className="flex items-center gap-1.5" role="tablist">
              <button
                id="lab-tab-tokens-btn"
                role="tab"
                aria-selected={activeLabTab === 'tokens'}
                onClick={() => setActiveLabTab('tokens')}
                className={`flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-mono transition-all cursor-pointer ${
                  activeLabTab === 'tokens'
                    ? 'bg-[#00eeff] text-[#1f242d] font-bold shadow-[0_0_10px_#00eeff]'
                    : 'text-gray-300 hover:text-white hover:bg-[#323946]'
                }`}
              >
                <Sliders className="w-3 h-3" />
                <span>token_engine</span>
              </button>

              <button
                id="lab-tab-perf-btn"
                role="tab"
                aria-selected={activeLabTab === 'perf'}
                onClick={() => setActiveLabTab('perf')}
                className={`flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-mono transition-all cursor-pointer ${
                  activeLabTab === 'perf'
                    ? 'bg-[#00eeff] text-[#1f242d] font-bold shadow-[0_0_10px_#00eeff]'
                    : 'text-gray-300 hover:text-white hover:bg-[#323946]'
                }`}
              >
                <Activity className="w-3 h-3" />
                <span>inp_profiler</span>
              </button>

              <button
                id="lab-tab-fsm-btn"
                role="tab"
                aria-selected={activeLabTab === 'fsm'}
                onClick={() => setActiveLabTab('fsm')}
                className={`flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-mono transition-all cursor-pointer ${
                  activeLabTab === 'fsm'
                    ? 'bg-[#00eeff] text-[#1f242d] font-bold shadow-[0_0_10px_#00eeff]'
                    : 'text-gray-300 hover:text-white hover:bg-[#323946]'
                }`}
              >
                <Cpu className="w-3 h-3" />
                <span>fsm_inspector</span>
              </button>
            </div>
          </div>

          {/* Workbench Body */}
          <div className="p-6 sm:p-8 font-sans">
            {/* 1. Design Token Engine */}
            {activeLabTab === 'tokens' && (
              <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 items-start">
                {/* Controls */}
                <div className="lg:col-span-6 space-y-6">
                  <div className="space-y-1">
                    <h3 className="text-base font-bold text-white">
                      Dynamic Design Token &amp; Scale Synthesizer
                    </h3>
                    <p className="text-xs text-gray-300">
                      Tweak typographic curves and base grid tokens to see instant CSS custom property generation and WCAG compliance feedback.
                    </p>
                  </div>

                  {/* Sliders */}
                  <div className="space-y-4 font-mono text-xs bg-[#1f242d] p-4 rounded-xl border border-[#323946]">
                    <div className="space-y-1.5">
                      <div className="flex justify-between">
                        <span className="text-gray-400">base_grid_unit:</span>
                        <span className="font-bold text-white">{baseUnit}px</span>
                      </div>
                      <input
                        type="range"
                        id="token-base-grid-slider"
                        min="2"
                        max="8"
                        step="2"
                        value={baseUnit}
                        onChange={(e) => setBaseUnit(Number(e.target.value))}
                        className="w-full accent-[#00eeff]"
                      />
                    </div>

                    <div className="space-y-1.5">
                      <div className="flex justify-between">
                        <span className="text-gray-400">modular_scale_ratio:</span>
                        <span className="font-bold text-[#00eeff]">
                          {modularRatio === 1.125
                            ? '1.125 (Major Second)'
                            : modularRatio === 1.25
                            ? '1.250 (Major Third)'
                            : '1.333 (Perfect Fourth)'}
                        </span>
                      </div>
                      <input
                        type="range"
                        id="token-modular-ratio-slider"
                        min="1.125"
                        max="1.333"
                        step="0.0625"
                        value={modularRatio}
                        onChange={(e) => setModularRatio(Number(e.target.value))}
                        className="w-full accent-[#00eeff]"
                      />
                    </div>

                    <div className="space-y-1.5">
                      <div className="flex justify-between">
                        <span className="text-gray-400">primary_brand_hue:</span>
                        <span className="font-bold text-white">{accentHue}°</span>
                      </div>
                      <input
                        type="range"
                        id="token-brand-hue-slider"
                        min="0"
                        max="360"
                        step="1"
                        value={accentHue}
                        onChange={(e) => setAccentHue(Number(e.target.value))}
                        className="w-full accent-[#00eeff]"
                      />
                    </div>
                  </div>

                  {/* Live Rendered Typography Preview */}
                  <div className="p-4 bg-[#1f242d] rounded-xl border border-[#323946] space-y-2">
                    <span className="text-xs font-mono text-gray-400 uppercase">Live Typographic Hierarchy Preview:</span>
                    <div className="space-y-1 text-white">
                      <p style={{ fontSize: `${(1 * modularRatio * modularRatio * modularRatio).toFixed(2)}rem` }} className="font-bold tracking-tight">
                        Display Heading
                      </p>
                      <p style={{ fontSize: `${(1 * modularRatio * modularRatio).toFixed(2)}rem` }} className="font-semibold text-gray-200">
                        Section Subheading
                      </p>
                      <p style={{ fontSize: '1rem' }} className="text-gray-400">
                        Body Text (16px base baseline)
                      </p>
                    </div>
                  </div>
                </div>

                {/* Right: Code Output */}
                <div className="lg:col-span-6 bg-[#1f242d] p-6 rounded-xl border border-[#323946] space-y-4">
                  <div className="flex items-center justify-between border-b border-[#323946] pb-3 font-mono text-xs">
                    <span className="text-gray-400">tokens.generated.css</span>
                    <button
                      onClick={handleCopyTokens}
                      className="flex items-center gap-1 text-[11px] px-2.5 py-1 rounded bg-[#323946] text-[#00eeff] hover:bg-[#00eeff] hover:text-[#1f242d] transition-colors cursor-pointer"
                    >
                      {tokenCopied ? <Check className="w-3 h-3" /> : <Copy className="w-3 h-3" />}
                      <span>{tokenCopied ? 'Copied' : 'Copy Tokens'}</span>
                    </button>
                  </div>

                  <pre className="font-mono text-xs text-[#00eeff] overflow-x-auto p-3 bg-[#181d25] rounded-xl border border-[#323946] leading-relaxed">
                    <code>{generatedCss}</code>
                  </pre>
                </div>
              </div>
            )}

            {/* 2. INP Profiler */}
            {activeLabTab === 'perf' && (
              <div className="space-y-6">
                <div className="flex flex-wrap items-center justify-between gap-4">
                  <div>
                    <h3 className="text-base font-bold text-white">Main Thread INP &amp; Render Stress Profiler</h3>
                    <p className="text-xs text-gray-300">Test how requestAnimationFrame batching avoids main thread locking during heavy DOM generation.</p>
                  </div>

                  <div className="flex items-center gap-3">
                    <button
                      onClick={runBenchmark}
                      disabled={isRendering}
                      className="px-4 py-2 rounded-xl bg-[#00eeff] text-[#1f242d] font-mono text-xs font-bold hover:bg-[#55f3ff] hover:shadow-[0_0_15px_#00eeff] transition-all flex items-center gap-1.5 cursor-pointer disabled:opacity-50"
                    >
                      <Play className="w-3.5 h-3.5" />
                      <span>{isRendering ? 'Benchmarking...' : 'Execute Benchmark'}</span>
                    </button>
                  </div>
                </div>

                <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                  <div className="p-4 bg-[#1f242d] rounded-xl border border-[#323946] space-y-2">
                    <span className="text-xs font-mono text-gray-400">Execution Strategy</span>
                    <div className="flex gap-2">
                      <button
                        onClick={() => setRenderMode('raf-batched')}
                        className={`px-3 py-1.5 rounded-lg text-xs font-mono transition-all cursor-pointer ${
                          renderMode === 'raf-batched'
                            ? 'bg-[#00eeff] text-[#1f242d] font-bold'
                            : 'bg-[#323946] text-gray-300'
                        }`}
                      >
                        RAF Batched (Non-blocking)
                      </button>
                      <button
                        onClick={() => setRenderMode('naive-sync')}
                        className={`px-3 py-1.5 rounded-lg text-xs font-mono transition-all cursor-pointer ${
                          renderMode === 'naive-sync'
                            ? 'bg-rose-500 text-white font-bold'
                            : 'bg-[#323946] text-gray-300'
                        }`}
                      >
                        Naive Sync (Blocking)
                      </button>
                    </div>
                  </div>

                  <div className="p-4 bg-[#1f242d] rounded-xl border border-[#323946] space-y-1">
                    <span className="text-xs font-mono text-gray-400">Last Execution Latency:</span>
                    <div className="text-2xl font-mono font-bold text-[#00eeff]">
                      {lastRenderTime !== null ? `${lastRenderTime} ms` : 'Awaiting trigger'}
                    </div>
                  </div>
                </div>

                <div className="p-4 bg-[#181d25] rounded-xl border border-[#323946] font-mono text-xs space-y-1 text-[#00eeff]">
                  <span className="text-gray-400 block mb-2">// telemetry_event_stream:</span>
                  {perfLog.map((log, i) => (
                    <div key={i} className="flex items-start gap-2">
                      <span className="text-gray-500">&gt;</span>
                      <span>{log}</span>
                    </div>
                  ))}
                </div>
              </div>
            )}

            {/* 3. FSM Inspector */}
            {activeLabTab === 'fsm' && (
              <div className="space-y-6">
                <div>
                  <h3 className="text-base font-bold text-white">Algebraic State Machine (FSM) Inspector</h3>
                  <p className="text-xs text-gray-300">Prevent impossible UI states by enforcing strict mathematical state transitions.</p>
                </div>

                <div className="flex flex-wrap items-center gap-3">
                  <span className="text-xs font-mono text-gray-400">Current State:</span>
                  <span className="px-3 py-1 rounded-full text-xs font-mono font-bold bg-[#00eeff] text-[#1f242d] shadow-[0_0_10px_#00eeff]">
                    {fsmState}
                  </span>
                </div>

                <div className="flex flex-wrap gap-2">
                  <button
                    onClick={() => triggerFsmTransition('FETCH')}
                    className="px-3.5 py-1.5 bg-[#1f242d] text-white hover:text-[#00eeff] hover:border-[#00eeff] border border-[#323946] rounded-lg text-xs font-mono transition-all cursor-pointer"
                  >
                    Action: FETCH
                  </button>
                  <button
                    onClick={() => triggerFsmTransition('RESOLVE')}
                    className="px-3.5 py-1.5 bg-[#1f242d] text-white hover:text-[#00eeff] hover:border-[#00eeff] border border-[#323946] rounded-lg text-xs font-mono transition-all cursor-pointer"
                  >
                    Action: RESOLVE (Success)
                  </button>
                  <button
                    onClick={() => triggerFsmTransition('REJECT')}
                    className="px-3.5 py-1.5 bg-[#1f242d] text-white hover:text-rose-400 hover:border-rose-400 border border-[#323946] rounded-lg text-xs font-mono transition-all cursor-pointer"
                  >
                    Action: REJECT (Error)
                  </button>
                  <button
                    onClick={() => triggerFsmTransition('RESET')}
                    className="px-3.5 py-1.5 bg-[#323946] text-gray-300 hover:text-white rounded-lg text-xs font-mono transition-all cursor-pointer"
                  >
                    Action: RESET
                  </button>
                </div>

                <div className="p-4 bg-[#181d25] rounded-xl border border-[#323946] font-mono text-xs space-y-1">
                  <span className="text-gray-400 block mb-2">// state_transition_log:</span>
                  {fsmHistory.map((h, i) => (
                    <div key={i} className="flex justify-between text-gray-300">
                      <span className="text-[#00eeff]">&gt; TRANSITION_TO [{h.state}]</span>
                      <span className="text-gray-500">{h.timestamp}</span>
                    </div>
                  ))}
                </div>
              </div>
            )}
          </div>
        </div>
      </div>
    </section>
  );
};
