import React, { useState, useEffect, useRef } from 'react';
import { Terminal, Play, RotateCcw, Copy, Check, Sliders, Activity, Cpu, Sparkles, CheckCircle2, AlertTriangle } from 'lucide-react';
import { useToast } from './Toast';

export const ComponentLab: React.FC = () => {
  const { showToast } = useToast();
  const [activeLabTab, setActiveLabTab] = useState<'tokens' | 'perf' | 'fsm'>('tokens');

  // --- 1. Design Token State ---
  const [baseUnit, setBaseUnit] = useState<number>(4);
  const [modularRatio, setModularRatio] = useState<number>(1.25); // Major Third
  const [accentHue, setAccentHue] = useState<number>(227); // Cobalt
  const [tokenCopied, setTokenCopied] = useState<boolean>(false);

  // Derive colors and scales
  const primaryColor = `hsl(${accentHue}, 100%, 59%)`;
  const primaryHover = `hsl(${accentHue}, 100%, 50%)`;
  const primaryMuted = `hsl(${accentHue}, 100%, 96%)`;

  // Calculate contrast against white (#FFFFFF)
  // Simplified relative luminance for HSL
  const isHighContrast = accentHue >= 200 && accentHue <= 260; // Blue/indigo passes AAA on white easily with dark text

  const generatedCss = `/* Generated by Brand Identity Generator & Token Engine */
:root {
  --spacing-base: ${baseUnit}px;
  --spacing-sm: ${baseUnit * 2}px;
  --spacing-md: ${baseUnit * 4}px;
  --spacing-lg: ${baseUnit * 6}px;

  --font-step-0: 1.000rem; /* 16px */
  --font-step-1: ${(1 * modularRatio).toFixed(3)}rem;
  --font-step-2: ${(1 * modularRatio * modularRatio).toFixed(3)}rem;
  --font-step-3: ${(1 * modularRatio * modularRatio * modularRatio).toFixed(3)}rem;

  --color-accent-primary: ${primaryColor};
  --color-accent-hover: ${primaryHover};
  --color-accent-subtle: ${primaryMuted};
}`;

  const handleCopyTokens = () => {
    navigator.clipboard.writeText(generatedCss);
    setTokenCopied(true);
    showToast('Design token CSS variables copied to clipboard');
    setTimeout(() => setTokenCopied(false), 2500);
  };

  // --- 2. Perf Stress Tester State ---
  const [itemCount, setItemCount] = useState<number>(1000);
  const [isRendering, setIsRendering] = useState<boolean>(false);
  const [lastRenderTime, setLastRenderTime] = useState<number | null>(null);
  const [renderMode, setRenderMode] = useState<'raf-batched' | 'naive-sync'>('raf-batched');
  const [perfLog, setPerfLog] = useState<string[]>([
    'Telemetry initialized with PerformanceObserver.',
    'Ready for DOM rendering stress benchmark.',
  ]);

  const runBenchmark = () => {
    setIsRendering(true);
    const start = performance.now();

    if (renderMode === 'raf-batched') {
      requestAnimationFrame(() => {
        const delta = performance.now() - start;
        setLastRenderTime(Math.round(delta * 10) / 10);
        setIsRendering(false);
        setPerfLog((prev) => [
          `[RAF Batched] Rendered ${itemCount} virtual items in ${delta.toFixed(2)}ms (60 FPS locked)`,
          ...prev.slice(0, 4),
        ]);
        showToast(`Benchmark completed in ${delta.toFixed(2)}ms`, 'success');
      });
    } else {
      // Simulate synchronous heavy layout calculation
      let sum = 0;
      for (let i = 0; i < itemCount * 1200; i++) {
        sum += Math.sqrt(i);
      }
      const delta = performance.now() - start;
      setLastRenderTime(Math.round(delta * 10) / 10);
      setIsRendering(false);
      setPerfLog((prev) => [
        `[Naive Sync] Main thread blocked for ${delta.toFixed(2)}ms (Long-Task Flagged!)`,
        ...prev.slice(0, 4),
      ]);
      showToast(`Main thread blocked for ${delta.toFixed(2)}ms`, 'info');
    }
  };

  // --- 3. Finite State Machine State ---
  type State = 'idle' | 'fetching' | 'revalidating' | 'success' | 'error';
  const [fsmState, setFsmState] = useState<State>('idle');
  const [fsmHistory, setFsmHistory] = useState<{ state: State; timestamp: string }[]>([
    { state: 'idle', timestamp: '00:00:00' },
  ]);

  const transitionTo = (nextState: State) => {
    const time = new Date().toLocaleTimeString();
    setFsmState(nextState);
    setFsmHistory((prev) => [{ state: nextState, timestamp: time }, ...prev.slice(0, 5)]);
  };

  return (
    <section id="component-lab" className="py-24 sm:py-28 md:py-32 border-b border-[#E7E6E2]">
      <div className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8">
        {/* Section Header with Clear Hierarchy and mb-14 spacing */}
        <div className="flex flex-col md:flex-row md:items-end justify-between gap-4 pb-8 mb-14 border-b border-[#E7E6E2]">
          <div className="space-y-2">
            <div className="flex items-center gap-2 text-xs font-mono text-[#64666E] uppercase tracking-wider">
              <span className="text-[#2F5CFF] font-bold">LAB.</span>
              <span>INTERACTIVE_WORKBENCH</span>
              <span className="text-[#9E9EA7]">//</span>
              <span>LIVE_ENGINEERING_BENCHMARKS</span>
            </div>
            <h2 className="text-3xl sm:text-4xl font-bold tracking-tight text-[#14151A]">
              Live Front-End Architecture Sandbox.
            </h2>
          </div>
          <p className="text-base text-[#555761] max-w-md font-sans leading-relaxed">
            Interactive experiments demonstrating token compilers, main-thread performance telemetry, and algebraic state machines.
          </p>
        </div>

        {/* Workbench Container */}
        <div className="rounded-xl border border-[#E7E6E2] bg-[#F4F3EF] overflow-hidden shadow-2xs">
          {/* Top Bar with Lab Switchers */}
          <div className="flex flex-wrap items-center justify-between px-4 sm:px-6 py-3 border-b border-[#E7E6E2] bg-[#EAE8E2]/70 gap-2">
            <div className="flex items-center gap-2">
              <Terminal className="w-4 h-4 text-[#2F5CFF]" />
              <span className="text-xs font-mono font-bold text-[#14151A]">
                lab_environment_v2.6
              </span>
            </div>

            <div className="flex items-center gap-1.5" role="tablist">
              <button
                id="lab-tab-tokens-btn"
                role="tab"
                aria-selected={activeLabTab === 'tokens'}
                onClick={() => setActiveLabTab('tokens')}
                className={`flex items-center gap-1.5 px-3 py-1.5 rounded text-xs font-mono transition-all ${
                  activeLabTab === 'tokens'
                    ? 'bg-[#14151A] text-white shadow-2xs'
                    : 'text-[#64666E] hover:text-[#14151A] hover:bg-[#E2E0D8]'
                }`}
              >
                <Sliders className="w-3 h-3" />
                <span>token_engine</span>
              </button>

              <button
                id="lab-tab-perf-btn"
                role="tab"
                aria-selected={activeLabTab === 'perf'}
                onClick={() => setActiveLabTab('perf')}
                className={`flex items-center gap-1.5 px-3 py-1.5 rounded text-xs font-mono transition-all ${
                  activeLabTab === 'perf'
                    ? 'bg-[#14151A] text-white shadow-2xs'
                    : 'text-[#64666E] hover:text-[#14151A] hover:bg-[#E2E0D8]'
                }`}
              >
                <Activity className="w-3 h-3" />
                <span>inp_profiler</span>
              </button>

              <button
                id="lab-tab-fsm-btn"
                role="tab"
                aria-selected={activeLabTab === 'fsm'}
                onClick={() => setActiveLabTab('fsm')}
                className={`flex items-center gap-1.5 px-3 py-1.5 rounded text-xs font-mono transition-all ${
                  activeLabTab === 'fsm'
                    ? 'bg-[#14151A] text-white shadow-2xs'
                    : 'text-[#64666E] hover:text-[#14151A] hover:bg-[#E2E0D8]'
                }`}
              >
                <Cpu className="w-3 h-3" />
                <span>fsm_inspector</span>
              </button>
            </div>
          </div>

          {/* Workbench Body */}
          <div className="p-6 sm:p-8 font-sans">
            {/* 1. Design Token Engine */}
            {activeLabTab === 'tokens' && (
              <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 items-start">
                {/* Controls */}
                <div className="lg:col-span-6 space-y-6">
                  <div className="space-y-1">
                    <h3 className="text-base font-bold text-[#14151A]">
                      Dynamic Design Token &amp; Scale Synthesizer
                    </h3>
                    <p className="text-xs text-[#64666E]">
                      Tweak typographic curves and base grid tokens to see instant CSS custom property generation and WCAG compliance feedback.
                    </p>
                  </div>

                  {/* Sliders */}
                  <div className="space-y-4 font-mono text-xs bg-white p-4 rounded-lg border border-[#E7E6E2]">
                    <div className="space-y-1.5">
                      <div className="flex justify-between">
                        <span className="text-[#64666E]">base_grid_unit:</span>
                        <span className="font-bold text-[#14151A]">{baseUnit}px</span>
                      </div>
                      <input
                        type="range"
                        id="token-base-grid-slider"
                        min="2"
                        max="8"
                        step="2"
                        value={baseUnit}
                        onChange={(e) => setBaseUnit(Number(e.target.value))}
                        className="w-full accent-[#2F5CFF]"
                      />
                    </div>

                    <div className="space-y-1.5">
                      <div className="flex justify-between">
                        <span className="text-[#64666E]">modular_scale_ratio:</span>
                        <span className="font-bold text-[#2F5CFF]">
                          {modularRatio === 1.125
                            ? '1.125 (Major Second)'
                            : modularRatio === 1.25
                            ? '1.250 (Major Third)'
                            : '1.333 (Perfect Fourth)'}
                        </span>
                      </div>
                      <input
                        type="range"
                        id="token-modular-ratio-slider"
                        min="1.125"
                        max="1.333"
                        step="0.0625"
                        value={modularRatio}
                        onChange={(e) => setModularRatio(Number(e.target.value))}
                        className="w-full accent-[#2F5CFF]"
                      />
                    </div>

                    <div className="space-y-1.5">
                      <div className="flex justify-between">
                        <span className="text-[#64666E]">primary_brand_hue:</span>
                        <span className="font-bold text-[#14151A]">{accentHue}°</span>
                      </div>
                      <input
                        type="range"
                        id="token-brand-hue-slider"
                        min="0"
                        max="360"
                        value={accentHue}
                        onChange={(e) => setAccentHue(Number(e.target.value))}
                        className="w-full accent-[#2F5CFF]"
                      />
                    </div>
                  </div>

                  {/* Live Rendered Component Preview */}
                  <div className="space-y-2">
                    <span className="text-xs font-mono text-[#64666E] uppercase">Live Synthesized UI Sample:</span>
                    <div
                      className="p-4 rounded-lg border border-[#E7E6E2] bg-white space-y-3 transition-all"
                      style={{
                        padding: `${baseUnit * 4}px`,
                      }}
                    >
                      <div className="flex items-center justify-between">
                        <span
                          className="font-bold transition-all text-[#14151A]"
                          style={{ fontSize: `${modularRatio * 1.1}rem` }}
                        >
                          Tokenized Heading
                        </span>
                        <span
                          className="px-2.5 py-1 rounded text-xs font-mono font-medium transition-colors"
                          style={{
                            backgroundColor: primaryMuted,
                            color: primaryColor,
                            border: `1px solid ${primaryColor}`,
                          }}
                        >
                          preview_badge
                        </span>
                      </div>
                      <p className="text-xs text-[#555761] leading-relaxed">
                        This component dynamically adapts its padding, font scale, and palette strictly from the generated CSS tokens.
                      </p>
                      <button
                        className="px-4 py-2 rounded text-xs font-mono font-medium text-white transition-all shadow-xs"
                        style={{
                          backgroundColor: primaryColor,
                          padding: `${baseUnit * 2}px ${baseUnit * 4}px`,
                        }}
                      >
                        Sample Action
                      </button>
                    </div>
                  </div>
                </div>

                {/* Right: Compiled CSS Output */}
                <div className="lg:col-span-6 space-y-3">
                  <div className="flex items-center justify-between">
                    <span className="text-xs font-mono text-[#64666E] uppercase flex items-center gap-1.5">
                      <Terminal className="w-3.5 h-3.5 text-[#2F5CFF]" />
                      <span>Compiled CSS Tokens Output</span>
                    </span>

                    <button
                      id="copy-generated-tokens-btn"
                      onClick={handleCopyTokens}
                      className="flex items-center gap-1 text-xs font-mono px-2.5 py-1 rounded bg-white border border-[#D5D4CE] hover:bg-[#F4F3EF] text-[#14151A] transition-colors"
                    >
                      {tokenCopied ? <Check className="w-3.5 h-3.5 text-[#1FAA6E]" /> : <Copy className="w-3.5 h-3.5" />}
                      <span>{tokenCopied ? 'copied' : 'copy_css'}</span>
                    </button>
                  </div>

                  <div className="rounded-lg bg-[#14151A] text-[#FAFAF8] p-4 font-mono text-xs overflow-x-auto border border-[#2B2D37] shadow-inner max-h-[360px]">
                    <pre className="text-emerald-400/90 leading-relaxed font-mono">
                      <code>{generatedCss}</code>
                    </pre>
                  </div>

                  <div className="flex items-center gap-2 text-xs font-mono text-[#64666E]">
                    <CheckCircle2 className="w-4 h-4 text-[#1FAA6E]" />
                    <span>Zero-runtime: Compiles to native browser CSS custom properties</span>
                  </div>
                </div>
              </div>
            )}

            {/* 2. Web Vitals INP & Frame Profiler */}
            {activeLabTab === 'perf' && (
              <div className="space-y-6">
                <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
                  <div className="space-y-1">
                    <h3 className="text-base font-bold text-[#14151A]">
                      Main Thread Scheduling &amp; Long Animation Frame Profiler
                    </h3>
                    <p className="text-xs text-[#64666E]">
                      Test how non-blocking requestAnimationFrame batching preserves sub-50ms INP compared to unthrottled synchronous render loops.
                    </p>
                  </div>

                  <button
                    id="run-perf-benchmark-btn"
                    onClick={runBenchmark}
                    disabled={isRendering}
                    className="inline-flex items-center gap-2 px-5 py-2.5 rounded-lg bg-[#2F5CFF] text-white text-xs font-mono font-medium hover:bg-[#254BD8] transition-colors shadow-xs shrink-0"
                  >
                    <Play className="w-3.5 h-3.5 fill-current" />
                    <span>{isRendering ? 'profiling...' : 'run_stress_benchmark'}</span>
                  </button>
                </div>

                {/* Configuration Bar */}
                <div className="grid grid-cols-1 sm:grid-cols-3 gap-4 font-mono text-xs bg-white p-4 rounded-lg border border-[#E7E6E2]">
                  <div>
                    <span className="text-[#64666E] block mb-1">render_strategy:</span>
                    <div className="flex gap-2">
                      <button
                        onClick={() => setRenderMode('raf-batched')}
                        className={`px-2.5 py-1 rounded ${
                          renderMode === 'raf-batched'
                            ? 'bg-[#14151A] text-white'
                            : 'bg-[#F4F3EF] text-[#64666E]'
                        }`}
                      >
                        RAF Batched
                      </button>
                      <button
                        onClick={() => setRenderMode('naive-sync')}
                        className={`px-2.5 py-1 rounded ${
                          renderMode === 'naive-sync'
                            ? 'bg-[#14151A] text-white'
                            : 'bg-[#F4F3EF] text-[#64666E]'
                        }`}
                      >
                        Naive Sync
                      </button>
                    </div>
                  </div>

                  <div>
                    <span className="text-[#64666E] block mb-1">simulated_nodes:</span>
                    <div className="flex gap-2">
                      {[500, 1000, 2500].map((count) => (
                        <button
                          key={count}
                          onClick={() => setItemCount(count)}
                          className={`px-2.5 py-1 rounded ${
                            itemCount === count
                              ? 'bg-[#2F5CFF] text-white'
                              : 'bg-[#F4F3EF] text-[#64666E]'
                          }`}
                        >
                          {count}
                        </button>
                      ))}
                    </div>
                  </div>

                  <div>
                    <span className="text-[#64666E] block mb-1">last_frame_duration:</span>
                    <span className="text-base font-bold text-[#14151A]">
                      {lastRenderTime !== null ? `${lastRenderTime} ms` : '—'}
                    </span>
                  </div>
                </div>

                {/* Telemetry Terminal Output */}
                <div className="space-y-2">
                  <span className="text-xs font-mono text-[#64666E] uppercase">PerformanceObserver Output Stream:</span>
                  <div className="p-4 bg-[#14151A] text-emerald-400 font-mono text-xs rounded-lg border border-[#2B2D37] space-y-1.5 min-h-[140px]">
                    {perfLog.map((log, i) => (
                      <div key={i} className="flex items-start gap-2">
                        <span className="text-[#64666E]">&gt;</span>
                        <span>{log}</span>
                      </div>
                    ))}
                  </div>
                </div>
              </div>
            )}

            {/* 3. Finite State Machine Inspector */}
            {activeLabTab === 'fsm' && (
              <div className="space-y-6">
                <div className="space-y-1">
                  <h3 className="text-base font-bold text-[#14151A]">
                    Algebraic Finite State Machine Visualizer
                  </h3>
                  <p className="text-xs text-[#64666E]">
                    Simulate strict state transitions that prevent impossible UI states (e.g. data cannot be read while in error state).
                  </p>
                </div>

                {/* Interactive State Nodes */}
                <div className="grid grid-cols-2 sm:grid-cols-5 gap-3 font-mono text-xs">
                  {(['idle', 'fetching', 'revalidating', 'success', 'error'] as State[]).map((st) => (
                    <button
                      key={st}
                      id={`fsm-btn-${st}`}
                      onClick={() => transitionTo(st)}
                      className={`p-3 rounded-lg border text-center transition-all ${
                        fsmState === st
                          ? 'bg-[#14151A] text-white border-[#14151A] shadow-md scale-105'
                          : 'bg-white text-[#64666E] border-[#E7E6E2] hover:border-[#D5D4CE]'
                      }`}
                    >
                      <span className="block text-[10px] text-[#9E9EA7] uppercase">STATE</span>
                      <span className="font-bold">{st}</span>
                    </button>
                  ))}
                </div>

                {/* Active State Details */}
                <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
                  <div className="lg:col-span-6 p-4 rounded-lg bg-white border border-[#E7E6E2] space-y-3 font-mono text-xs">
                    <span className="text-[#64666E] uppercase block font-bold">Current State Snapshot:</span>
                    <div className="p-3 bg-[#F4F3EF] rounded border border-[#E7E6E2] space-y-1">
                      <div><span className="text-[#64666E]">status:</span> <span className="text-[#2F5CFF] font-bold">&quot;{fsmState}&quot;</span></div>
                      <div><span className="text-[#64666E]">can_revalidate:</span> <span className="text-[#14151A]">{fsmState === 'success' ? 'true' : 'false'}</span></div>
                      <div><span className="text-[#64666E]">has_error_payload:</span> <span className="text-[#14151A]">{fsmState === 'error' ? 'true' : 'false'}</span></div>
                    </div>
                  </div>

                  <div className="lg:col-span-6 p-4 rounded-lg bg-white border border-[#E7E6E2] space-y-2 font-mono text-xs">
                    <span className="text-[#64666E] uppercase block font-bold">Transition Audit Trail:</span>
                    <ul className="space-y-1.5 max-h-[140px] overflow-y-auto text-[11px]">
                      {fsmHistory.map((h, i) => (
                        <li key={i} className="flex justify-between text-[#44464F] border-b border-[#F4F3EF] pb-1">
                          <span>transition -&gt; <strong className="text-[#14151A]">{h.state}</strong></span>
                          <span className="text-[#9E9EA7]">{h.timestamp}</span>
                        </li>
                      ))}
                    </ul>
                  </div>
                </div>
              </div>
            )}
          </div>
        </div>
      </div>
    </section>
  );
};
